/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cs234project;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author mjsanchez
 */
public class CashPaymentGUI extends javax.swing.JFrame {
    private Customer customer;
    private Cart cart;
    private double tax;
    private double totalDue;
    /**
     * Creates new form CashPaymentGUI
     */
    public CashPaymentGUI() {
        
    }
    public CashPaymentGUI(Customer customer, Cart cart) {
        this.customer = customer;
        this.cart = cart;
        totalDue = cart.getTotal() + (cart.getTotal() * cart.getTax());
        lblDue = new JLabel();
        lblDue.setText("0");
        lblDue.setVisible(false);
        getContentPane().setBackground(Color.darkGray);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCashAmount = new javax.swing.JLabel();
        tfCashGiven = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblDue = new javax.swing.JLabel();
        btnCompleteTrans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 0));

        lblCashAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblCashAmount.setText("Cash Amount");

        tfCashGiven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCashGivenActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total: $" + String.format("%.2f", (cart.getTotal() + (cart.getTotal() * cart.getTax()))));

        lblDue.setForeground(new java.awt.Color(255, 255, 255));

        btnCompleteTrans.setText("Complete Transaction");
        btnCompleteTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteTransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDue, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCompleteTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCashAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(tfCashGiven, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCashAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCashGiven))
                .addGap(18, 18, 18)
                .addComponent(lblDue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnCompleteTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        setSize(new java.awt.Dimension(400, 328));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfCashGivenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCashGivenActionPerformed
        double num;
        try {
            num = Double.parseDouble(tfCashGiven.getText());
            String changeText;
         //String amountDue;
            double change = 0;
            String cashGiven = tfCashGiven.getText();
            double cash = Double.parseDouble(cashGiven);
            totalDue = cart.getTotal() + (cart.getTotal() * cart.getTax());
            if (cash >= totalDue) {
                change = cash - totalDue;
                String text = String.format("%.2f", change);
                changeText = "Change Due: $" + text;
                lblDue.setVisible(true);
                lblDue.setText(changeText);
        } else {
            change = totalDue - cash;
            String text = String.format("%.2f", change);
            changeText = "Amount Due: $" + text;
            lblDue.setVisible(true);
            lblDue.setText(changeText);
        }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Please enter a numerical amount");
            tfCashGiven.setText("");
        }
    }//GEN-LAST:event_tfCashGivenActionPerformed

    private void btnCompleteTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteTransActionPerformed
    try{
        String input = tfCashGiven.getText().trim();
        if (input.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a cash amount.");
            return;
        }
        
        double cash = Double.parseDouble(input);
        totalDue = cart.getTotal() + (cart.getTotal() * cart.getTax());
        
        if(cash >= totalDue) {
            double change = cash - totalDue;
            
            if(customer != null && !customer.getFirstName().equalsIgnoreCase("Guest")){
                customer.addPoints(totalDue);
                JOptionPane.showMessageDialog(this, customer.getFirstName() + " earned " + customer.getPoints() + " points!");
            }
            
            JOptionPane.showMessageDialog(this, "Transaction Complete.\nChange Due: $" + String.format("%.2f", change));
            cart.emptyCart();
            this.dispose();
        }else{
            double shortage = totalDue - cash;
            JOptionPane.showMessageDialog(this, "Insufficent amount.\nStill owed: $" + String.format("%.2f", shortage));
        }
        }catch (NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Invalid input. Please enter a numerical value.");
                }
    }//GEN-LAST:event_btnCompleteTransActionPerformed
//    public String getChange() {
//        String changeText;
//        //String amountDue;
//        double change = 0;
//        String cashGiven = tfCashGiven.getText();
//        double cash = Double.parseDouble(cashGiven);
//        double totalDue = cart.getTotal() + (cart.getTotal() * cart.getTax());
//        if (cash >= totalDue) {
//            change = cash - totalDue;
//            String text = String.format("%.2f", change);
//            changeText = "Change Due: $" + text;
//            return changeText;
//        } else {
//            change = totalDue - cash;
//            String text = String.format("%.2f", change);
//            changeText = "Amount Due: $" + text;
//            return changeText;
//        }
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashPaymentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompleteTrans;
    private javax.swing.JLabel lblCashAmount;
    private javax.swing.JLabel lblDue;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField tfCashGiven;
    // End of variables declaration//GEN-END:variables
}
