/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael Sanchez
 */

//Variable definitions for this class
public class CashPaymentGUI extends javax.swing.JFrame {
    private Customer customer;
    private Cart cart;
    private double tax;
    private double total;
    private double totalWithTax;
    private double change;
    private double paid;
    private double balance;
    /**
     * Creates new form CashPaymentGUI
     */
    
    //generic constructor
    public CashPaymentGUI() {
      initComponents();  
    }
    
    //Constructor initializing variables
    public CashPaymentGUI(Customer customer, Cart cart) {
        this.customer = customer;
        this.cart = cart;
        total = cart.getTotal();
        totalWithTax = cart.getTotalWithTax();
        lblDue = new JLabel();
        this.change = 0.0;
        this.paid = 0.0;
        this.balance = 0.0;
        lblDue.setText("0");
        lblDue.setVisible(false);
        getContentPane().setBackground(Color.darkGray);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCashAmount = new javax.swing.JLabel();
        tfCashGiven = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblDue = new javax.swing.JLabel();
        btnCompleteTrans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 0));

        lblCashAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblCashAmount.setText("Cash Amount");

        tfCashGiven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCashGivenActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total: $" + String.format("%.2f", (cart.getTotalWithTax())));

        lblDue.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDue.setForeground(new java.awt.Color(255, 255, 255));

        btnCompleteTrans.setText("Complete Transaction");
        btnCompleteTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteTransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCompleteTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCashAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(tfCashGiven, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblDue, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCashAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCashGiven))
                .addGap(32, 32, 32)
                .addComponent(lblDue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnCompleteTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        setSize(new java.awt.Dimension(400, 328));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Method that acts when a value is entered into the text field tfCashGiven
    private void tfCashGivenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCashGivenActionPerformed
        double num;
        try {
            //converts the text input to a double
            num = Double.parseDouble(tfCashGiven.getText());
            String changeText;
         //String amountDue;
            change = 0;
            //converts the text input to a double
            String cashGiven = tfCashGiven.getText();
            //Assignes paid value as cashGiven
            paid = Double.parseDouble(cashGiven);
            if (paid >= totalWithTax) {
                change = paid - totalWithTax;
                cart.setAmountPaid(num);
                /**if paid is greater than what customer owes, value change is 
                 * assigned the value of paid minus the owed total and then formatted
                 * to 2 decimal places below.
                 */
                String text = String.format("%.2f", change);
                changeText = "Change Due: $" + text;
                
                lblDue.setForeground(Color.green);
                lblDue.setVisible(true);
                lblDue.setText(changeText);
        /** 
         * If the amount owed is greater than what was paid, then a balance value
         * is assigned, text is changed to red.
         */
        } else {
            change = totalWithTax - paid;
            cart.setTotalWithTax(change);
            cart.setAmountPaid(num);
            balance = change;
            String text = String.format("%.2f", change);
            changeText = "Amount Due: $" + text;
            lblDue.setForeground(Color.red);
            lblDue.setVisible(true);
            lblDue.setText(changeText);
        }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Please enter a numerical amount");
            tfCashGiven.setText("");
        }
    }//GEN-LAST:event_tfCashGivenActionPerformed
    
    //Method that checks if there is a balance owed
    private void btnCompleteTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteTransActionPerformed
        /**
         * If balance is owed then open a cashpayment window with remainder so 
         * customer can pay with a any payment option.
         */
        if (balance > 0) {
            this.setVisible(false);
            //System.out.print("total > 0" + cart.getTotalWithTax());
            Payment cash = new CashPayment(totalWithTax, paid);
            cash.addPayment(cash);
            new PaymentGUI(customer, cart, change, paid).setVisible(true);
        /**
         * If there is no balance, checks to see if the customer is a guest or 
         * a registered customer then prints receipt.  If registered points are 
         * added to the customer.
         */
        } else {
            //System.out.print("total < 0" + cart.getTotalWithTax());
            if (customer.getFirstName().equals("Guest")) {
                Payment cash = new CashPayment(totalWithTax, paid);
                cash.addPayment(cash);
                new ReceiptGUI(customer, cart, change, paid).setVisible(true);

            } else {
                double points = total/1;
                customer.addPoints(points);
                Payment cash = new CashPayment(totalWithTax, paid);
                cash.addPayment(cash);
                new ReceiptGUI(customer, cart, change, paid).setVisible(true);
            }   
        cart.emptyCart();
        double ap = cart.getAmountPaid();
        System.out.println("AmountPaid: " + ap);
        this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnCompleteTransActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashPaymentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompleteTrans;
    private javax.swing.JLabel lblCashAmount;
    private javax.swing.JLabel lblDue;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField tfCashGiven;
    // End of variables declaration//GEN-END:variables
}
