/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.Color;
import javax.swing.JLabel;

/**
 * @author Michael Sanchez
 */

//Variable definitions
public class CreditCardPaymentGUI extends javax.swing.JFrame {
    private Customer customer;
    private Cart cart;
    private double tax;
    private double total;
    private double totalWithTax;
    private double change;
    private double paid;
    private double balance;
    
    /**
     * Creates new form CreditCardPaymentGUI
     */
    public CreditCardPaymentGUI() {
        initComponents();
    }
    
    //Constuctor that initializes the variables
    public CreditCardPaymentGUI(Customer customer, Cart cart) {
        this.customer = customer;
        this.cart = cart;
        total = cart.getTotal();
        totalWithTax = cart.getTotalWithTax();
        this.change = 0.0;
        this.paid = 0.0;
        this.balance = 0.0;
        getContentPane().setBackground(Color.darkGray);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotal = new javax.swing.JLabel();
        lblCardName = new javax.swing.JLabel();
        tfCardName = new javax.swing.JTextField();
        lblCardNumber = new javax.swing.JLabel();
        tfCardNumber = new javax.swing.JTextField();
        lblExpDate = new javax.swing.JLabel();
        tfExpDate = new javax.swing.JTextField();
        lblSecurityNum = new javax.swing.JLabel();
        tfSecurityNum = new javax.swing.JTextField();
        Confirm = new javax.swing.JButton();
        lblCardLastName = new javax.swing.JLabel();
        tfCardLastName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total: $" + String.format("%.2f", (cart.getTotalWithTax())));

        lblCardName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCardName.setForeground(new java.awt.Color(255, 255, 255));
        lblCardName.setText("Holders First Name");

        tfCardName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCardNameActionPerformed(evt);
            }
        });

        lblCardNumber.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCardNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblCardNumber.setText("Credit Card Number");

        tfCardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCardNumberActionPerformed(evt);
            }
        });

        lblExpDate.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblExpDate.setForeground(new java.awt.Color(255, 255, 255));
        lblExpDate.setText("Expiration Date");

        tfExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfExpDateActionPerformed(evt);
            }
        });

        lblSecurityNum.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblSecurityNum.setForeground(new java.awt.Color(255, 255, 255));
        lblSecurityNum.setText("Security Number");

        tfSecurityNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSecurityNumActionPerformed(evt);
            }
        });

        Confirm.setText("Confirm");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        lblCardLastName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCardLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblCardLastName.setText("Holders LastName");

        tfCardLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCardLastNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCardName, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCardName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfCardNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfExpDate, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblExpDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfSecurityNum)
                                        .addComponent(lblSecurityNum, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                            .addComponent(tfCardLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCardLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCardName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCardName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCardLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCardLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSecurityNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSecurityNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(Confirm)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(387, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfCardNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCardNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCardNameActionPerformed

    private void tfCardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCardNumberActionPerformed

    private void tfExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfExpDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfExpDateActionPerformed

    private void tfSecurityNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSecurityNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSecurityNumActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        /**
         * Method that assigns the text for all text fields to creditCardPayment object
         * charges the card for the payment amount and adds points before showing receipt
         */
        double total = cart.getTotalWithTax();
        String fname = tfCardName.getText();
        String lname = tfCardLastName.getText();
        String ccnum = tfCardNumber.getText();
        String expDate = tfExpDate.getText();
        String secNum = tfSecurityNum.getText();
        int sec = Integer.parseInt(secNum);
        Payment credit = new CreditCardPayment(total, fname, lname, ccnum, expDate, sec);
        credit.addPayment(credit);
        //checks if customer is a registered customer, adds points if they are and prints receipt.
        if (customer.getFirstName().equals("Guest")) {
            cart.setAmountPaid(totalWithTax);
                new ReceiptGUI(customer, cart, change, totalWithTax).setVisible(true);

            } else {
                double points = total/1;
                customer.addPoints(points);
                cart.setAmountPaid(totalWithTax);
                new ReceiptGUI(customer, cart, change, totalWithTax).setVisible(true);
            }
        //System.out.println("complete, cart emptied, amountPaid ==0");   
        cart.emptyCart();
        //cart.setAmountPaid(0.0);
        double ap = cart.getAmountPaid();
        System.out.println("AmountPaid: " + ap);
        this.setVisible(false);
    }//GEN-LAST:event_ConfirmActionPerformed

    private void tfCardLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCardLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCardLastNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCardPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCardPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCardPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCardPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditCardPaymentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm;
    private javax.swing.JLabel lblCardLastName;
    private javax.swing.JLabel lblCardName;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblExpDate;
    private javax.swing.JLabel lblSecurityNum;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField tfCardLastName;
    private javax.swing.JTextField tfCardName;
    private javax.swing.JTextField tfCardNumber;
    private javax.swing.JTextField tfExpDate;
    private javax.swing.JTextField tfSecurityNum;
    // End of variables declaration//GEN-END:variables
}
