/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael Sanchez
 */

//variable definitions
public class CustomerMenuGui extends javax.swing.JFrame {
    private Customer current;
    private Staff staff;
    private Membership mem;
    private Authentication obauth;
    private EmployeeManager objman;
    private Authentication objauth;
    private Inventory inventory;
    private Cart cart;
    private HashSet<Customer> hashset;
    private ArrayList<Staff> alist;
    private ArrayList<Concession> prod;
    private ArrayList<Showtimes> shows;
    /**
     * Creates new form MainGui
     */
    
    public CustomerMenuGui() {
        
    }
    
    //Initializes variables in constructor
    public CustomerMenuGui(Customer customer, Staff staff, HashSet<Customer> hashset, Membership mem, Authentication obauth, ArrayList<Staff> alist, EmployeeManager objman, Authentication objauth, Inventory inventory, ArrayList<Concession> prod, Cart cart, ArrayList<Showtimes> shows) {
        this.current = new Customer();
        this.staff = staff;
        this.hashset = hashset;
        this.mem = mem;
        this.obauth = obauth;
        this.alist = alist;
        this.objman = objman;
        this.objauth = objauth;
        this.inventory = inventory;
        this.prod = prod;
        this.cart = cart;
        this.shows = shows;
        initComponents();
        
        getContentPane().setBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butCustLogin = new javax.swing.JButton();
        butCustReg = new javax.swing.JButton();
        butCustMainMenu = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        butLoginAsGuest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movie Theater");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        butCustLogin.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butCustLogin.setText("Login");
        butCustLogin.setAutoscrolls(true);
        butCustLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butCustLogin.setContentAreaFilled(false);
        butCustLogin.setOpaque(true);
        butCustLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCustLoginActionPerformed(evt);
            }
        });
        getContentPane().add(butCustLogin);
        butCustLogin.setBounds(150, 130, 220, 58);

        butCustReg.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butCustReg.setText("Registration");
        butCustReg.setAutoscrolls(true);
        butCustReg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butCustReg.setContentAreaFilled(false);
        butCustReg.setOpaque(true);
        butCustReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCustRegActionPerformed(evt);
            }
        });
        getContentPane().add(butCustReg);
        butCustReg.setBounds(150, 210, 220, 58);

        butCustMainMenu.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butCustMainMenu.setText("Exit to Main Menu");
        butCustMainMenu.setAutoscrolls(true);
        butCustMainMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butCustMainMenu.setContentAreaFilled(false);
        butCustMainMenu.setOpaque(true);
        butCustMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCustMainMenuActionPerformed(evt);
            }
        });
        getContentPane().add(butCustMainMenu);
        butCustMainMenu.setBounds(150, 370, 220, 58);

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Generic");
        getContentPane().add(lblTitle1);
        lblTitle1.setBounds(110, 30, 198, 46);

        lblTitle2.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 153, 0));
        lblTitle2.setText("Movie Theater");
        getContentPane().add(lblTitle2);
        lblTitle2.setBounds(190, 60, 255, 56);

        butLoginAsGuest.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butLoginAsGuest.setText("Login as Guest");
        butLoginAsGuest.setAutoscrolls(true);
        butLoginAsGuest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butLoginAsGuest.setContentAreaFilled(false);
        butLoginAsGuest.setOpaque(true);
        butLoginAsGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginAsGuestActionPerformed(evt);
            }
        });
        getContentPane().add(butLoginAsGuest);
        butLoginAsGuest.setBounds(150, 290, 220, 58);

        setSize(new java.awt.Dimension(543, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butCustLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCustLoginActionPerformed
    /**
     * Method for allowing customers to log in.  Prompts user for a phone number and verifies
     * that the phone number is the right length.  Then prompts for a password.
     */
    String pNum = JOptionPane.showInputDialog(this, "Enter your phone number.");
    if (pNum != null && !pNum.isEmpty()) {
        try {
            long inputNum = Long.parseLong(pNum);
            //CustomerLogin(current, hashset, mem, obauth);
            while (!pNum.matches("\\d{10}")) {
                JOptionPane.showInputDialog(this, "Invalid phone number entry.  Please try again.");
                pNum = JOptionPane.showInputDialog(this, "Enter your phone number.");
                inputNum = Long.parseLong(pNum);
            }
            //Casts the string input to long value.
            String pass = JOptionPane.showInputDialog(this, "Enter your password.");
            current = obauth.AuthenticateCustomer(inputNum, pass);
        } catch (NumberFormatException e) {
            
    }
    /**
     * if the user exists or is not a guest, continue to transaction menu, else, prompts user
     * to login as a guest and returns to customer menu.
     */
    if (current != null && current.getFirstName() != "Guest") {
        this.setVisible(false); 
        TransactionMenuGUI tm = new TransactionMenuGUI(current, staff, hashset, mem, obauth, alist, objman, objauth, inventory, prod, cart, shows);
        tm.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Not a member.  Please try again or login as guest.");
        }
    }

    
        //TransactionMenu(current, staff, hashset, mem, obauth, alist, objman, objauth, inventory, prod, cart, shows);
    }//GEN-LAST:event_butCustLoginActionPerformed

    private void butCustMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCustMainMenuActionPerformed
        //Returns to main menu.
        this.setVisible(false); new MainGui(current, staff, hashset, mem, obauth, alist, objman, objauth, inventory, prod, cart, shows).setVisible(true);
    }//GEN-LAST:event_butCustMainMenuActionPerformed

    private void butLoginAsGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginAsGuestActionPerformed
        //Allows the user to login as a guest.
        this.setVisible(false); 
        TransactionMenuGUI tm = new TransactionMenuGUI(current, staff, hashset, mem, obauth, alist, objman, objauth, inventory, prod, cart, shows);
        tm.setVisible(true);
    }//GEN-LAST:event_butLoginAsGuestActionPerformed

    private void butCustRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCustRegActionPerformed
        //Opens Customer registration frame.
        new CustomerRegistrationGui(hashset, mem, obauth).setVisible(true);
    }//GEN-LAST:event_butCustRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMenuGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCustLogin;
    private javax.swing.JButton butCustMainMenu;
    private javax.swing.JButton butCustReg;
    private javax.swing.JButton butLoginAsGuest;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    // End of variables declaration//GEN-END:variables
}
