/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cs234project;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Michael Sanchez
 */

//Variable definitions
public class GiftCardPaymentGUI extends javax.swing.JFrame {
    private Customer customer;
    private Cart cart;
    private double tax;
    private double total;
    private double totalWithTax;
    private double change;
    private double paid;
    private double balance;
    /**
     * Creates new form CreditCardPaymentGUI
     */
    public GiftCardPaymentGUI() {
        initComponents();
    }
    
    //Initializes variables
    public GiftCardPaymentGUI(Customer customer, Cart cart) {
        this.customer = customer;
        this.cart = cart;
        total = cart.getTotal();
        totalWithTax = cart.getTotalWithTax();
        this.change = 0.0;
        this.paid = 0.0;
        this.balance = 0.0;
        getContentPane().setBackground(Color.darkGray);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotal = new javax.swing.JLabel();
        lblCardNumber = new javax.swing.JLabel();
        tfCardNumber = new javax.swing.JTextField();
        lblExpDate = new javax.swing.JLabel();
        tfExpDate = new javax.swing.JTextField();
        Confirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total: $" + String.format("%.2f", (cart.getTotalWithTax())));

        lblCardNumber.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCardNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblCardNumber.setText("Credit Card Number");

        tfCardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCardNumberActionPerformed(evt);
            }
        });

        lblExpDate.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblExpDate.setForeground(new java.awt.Color(255, 255, 255));
        lblExpDate.setText("Expiration Date");

        tfExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfExpDateActionPerformed(evt);
            }
        });

        Confirm.setText("Confirm");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Confirm)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(356, 291));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfCardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCardNumberActionPerformed

    private void tfExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfExpDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfExpDateActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        /**
         * Assigns text field values to a new GiftCard Object and charges that 
         * object the total amount.  then checks to see if the current customer 
         * is a guest and if not, adds points before printing a receipt.
         */
        double total = cart.getTotalWithTax();
        String ccnum = tfCardNumber.getText();
        String expDate = tfExpDate.getText();
        Payment giftCard = new GiftCardPayment(total, ccnum, expDate);
        giftCard.addPayment(giftCard);
        if (customer.getFirstName().equals("Guest")) {
            cart.setAmountPaid(totalWithTax);
                new ReceiptGUI(customer, cart, change, totalWithTax).setVisible(true);

            } else {
                double points = total/1;
                customer.addPoints(points);
                cart.setAmountPaid(totalWithTax);
                new ReceiptGUI(customer, cart, change, totalWithTax).setVisible(true);
            }
        //System.out.println("complete, cart emptied, amountPaid ==0");   
        cart.emptyCart();
        //cart.setAmountPaid(0.0);
        double ap = cart.getAmountPaid();
        System.out.println("AmountPaid: " + ap);
        this.setVisible(false);
    }//GEN-LAST:event_ConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiftCardPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiftCardPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiftCardPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiftCardPaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiftCardPaymentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblExpDate;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField tfCardNumber;
    private javax.swing.JTextField tfExpDate;
    // End of variables declaration//GEN-END:variables
}
