/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cs234project;
import com.mycompany.cs234project.Inventory;
import com.mycompany.cs234project.Concession;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;
/**
 *
 * @author jbock
 */
public class InventoryMenuGui extends javax.swing.JFrame {
    private Customer current;
    private Staff staff;
    private Membership mem;
    private Authentication obauth;
    private EmployeeManager objman;
    private Authentication objauth;
    private Inventory inventory;
    private Cart cart;
    private HashSet<Customer> hashset;
    private ArrayList<Staff> alist;
    private ArrayList<Concession> prod;
    private ArrayList<Showtimes> shows;
    /**
     * Creates new form InventoryMenuGui
     */
    public InventoryMenuGui(Inventory inventory, ArrayList<Concession> prod) {
        this.inventory=inventory;
        this.prod=prod;
        initComponents();
        getContentPane().setBackground(Color.black);
    }

    private InventoryMenuGui() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butAddInventory = new javax.swing.JButton();
        butRemoveInventory = new javax.swing.JButton();
        butShowInventory = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        butStaffMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butAddInventory.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butAddInventory.setText("Add to Inventory");
        butAddInventory.setAutoscrolls(true);
        butAddInventory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butAddInventory.setContentAreaFilled(false);
        butAddInventory.setOpaque(true);
        butAddInventory.setPreferredSize(new java.awt.Dimension(184, 38));
        butAddInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddInventoryActionPerformed(evt);
            }
        });

        butRemoveInventory.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butRemoveInventory.setText("Remove Inventory");
        butRemoveInventory.setAutoscrolls(true);
        butRemoveInventory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butRemoveInventory.setContentAreaFilled(false);
        butRemoveInventory.setOpaque(true);
        butRemoveInventory.setPreferredSize(new java.awt.Dimension(184, 38));
        butRemoveInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRemoveInventoryActionPerformed(evt);
            }
        });

        butShowInventory.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butShowInventory.setText("Display Inventory");
        butShowInventory.setAutoscrolls(true);
        butShowInventory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butShowInventory.setContentAreaFilled(false);
        butShowInventory.setOpaque(true);
        butShowInventory.setPreferredSize(new java.awt.Dimension(184, 38));
        butShowInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butShowInventoryActionPerformed(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Generic");

        lblTitle2.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 153, 0));
        lblTitle2.setText("Movie Theater");

        butStaffMenu.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butStaffMenu.setText("Staff Menu");
        butStaffMenu.setAutoscrolls(true);
        butStaffMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butStaffMenu.setContentAreaFilled(false);
        butStaffMenu.setOpaque(true);
        butStaffMenu.setPreferredSize(new java.awt.Dimension(184, 38));
        butStaffMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butStaffMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butAddInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butShowInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butRemoveInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butStaffMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblTitle2)))
                .addGap(18, 18, 18)
                .addComponent(butShowInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butAddInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butRemoveInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butStaffMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butAddInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddInventoryActionPerformed
        new InventoryAdd(prod,inventory).setVisible(true);
    }//GEN-LAST:event_butAddInventoryActionPerformed

    private void butRemoveInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRemoveInventoryActionPerformed
        
    }//GEN-LAST:event_butRemoveInventoryActionPerformed

    private void butShowInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butShowInventoryActionPerformed
        JOptionPane.showMessageDialog(this, inventory.getProductList());
    }//GEN-LAST:event_butShowInventoryActionPerformed

    private void butStaffMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStaffMenuActionPerformed
        this.setVisible(false); new StaffMenuGui(current, staff, hashset, mem, obauth, alist, objman, objauth, inventory, prod, cart, shows).setVisible(true);
    }//GEN-LAST:event_butStaffMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryMenuGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAddInventory;
    private javax.swing.JButton butRemoveInventory;
    private javax.swing.JButton butShowInventory;
    private javax.swing.JButton butStaffMenu;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    // End of variables declaration//GEN-END:variables
}
