/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cs234project;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author mjsanchez
 */
public class MovieSelectionGUI2 extends javax.swing.JFrame {
    private Inventory inventory;
    private Cart cart;
    private ArrayList<Showtimes>shows;
    /**
     * Creates new form MovieSelectionGUI2
     */
    public MovieSelectionGUI2() {
        initComponents();
    }
    
    public MovieSelectionGUI2(Inventory inventory, Cart cart, ArrayList<Showtimes> shows) {
        this.inventory = inventory;
        this.cart = cart;
        this.shows = shows;
        getContentPane().setBackground(Color.darkGray);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMovie1 = new javax.swing.JPanel();
        lblMovie1Title = new javax.swing.JLabel();
        btnMovie1Time1 = new javax.swing.JButton();
        lblMovie1T1Rating = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMovieDescMovie1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMovie1.setBackground(new java.awt.Color(51, 51, 51));
        pnlMovie1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMovie1Title.setFont(new java.awt.Font("Bodoni 72", 1, 48)); // NOI18N
        lblMovie1Title.setForeground(new java.awt.Color(255, 255, 255));
        lblMovie1Title.setText(shows.get(0).getTitle()
        );

        btnMovie1Time1.setText(shows.get(0).getTime()
        );
        btnMovie1Time1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovie1Time1ActionPerformed(evt);
            }
        });

        lblMovie1T1Rating.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblMovie1T1Rating.setForeground(new java.awt.Color(255, 255, 255));
        lblMovie1T1Rating.setText("Rated: " + shows.get(0).getRating() + "   Runtime: " + shows.get(0).getRuntime()
        );

        taMovieDescMovie1.setEditable(false);
        taMovieDescMovie1.setBackground(new java.awt.Color(51, 51, 51));
        taMovieDescMovie1.setColumns(20);
        taMovieDescMovie1.setFont(new java.awt.Font("Helvetica Neue", 2, 18)); // NOI18N
        taMovieDescMovie1.setForeground(new java.awt.Color(255, 255, 255));
        taMovieDescMovie1.setLineWrap(true);
        taMovieDescMovie1.setRows(5);
        taMovieDescMovie1.setText(shows.get(0).getDesc()
        );
        taMovieDescMovie1.setWrapStyleWord(true);
        taMovieDescMovie1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        taMovieDescMovie1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(taMovieDescMovie1);

        javax.swing.GroupLayout pnlMovie1Layout = new javax.swing.GroupLayout(pnlMovie1);
        pnlMovie1.setLayout(pnlMovie1Layout);
        pnlMovie1Layout.setHorizontalGroup(
            pnlMovie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMovie1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMovie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMovie1T1Rating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMovie1Layout.createSequentialGroup()
                        .addComponent(lblMovie1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMovie1Time1)
                        .addGap(0, 115, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        pnlMovie1Layout.setVerticalGroup(
            pnlMovie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMovie1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMovie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMovie1Title, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMovie1Time1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMovie1T1Rating)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMovie1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMovie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMovie1Time1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovie1Time1ActionPerformed
        if(shows.get(0).getScreenType().equals("imax")) {
            Showtimes currentShow = new Showtimes();
            currentShow = shows.get(0);
            currentShow.displayShowSeating();
            String t = currentShow.getScreenType();
            this.setVisible(false); new ImaxSeatingGui(currentShow, t, cart).setVisible(true);
        }else {
            Showtimes currentShow = new Showtimes();
            currentShow = shows.get(0);
            currentShow.displayShowSeating();
            String t = currentShow.getScreenType();
            this.setVisible(false); new RegularSeatingGui(currentShow, t, cart).setVisible(true);
        }
    }//GEN-LAST:event_btnMovie1Time1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieSelectionGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieSelectionGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieSelectionGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieSelectionGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieSelectionGUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMovie1Time1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMovie1T1Rating;
    private javax.swing.JLabel lblMovie1Title;
    private javax.swing.JPanel pnlMovie1;
    private javax.swing.JTextArea taMovieDescMovie1;
    // End of variables declaration//GEN-END:variables
}
