/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cs234project;

import java.awt.Color;

/**
 *
 * @author mjsanchez
 */
public class PaymentGUI extends javax.swing.JFrame {
    private Customer current;
    private Cart cart;
    private double cash;
    private double am;
    /**
     * Creates new form PaymentGUI
     */
    public PaymentGUI() {
        
    }
    public PaymentGUI(Customer current, Cart cart) {
        this.current = current;
        this.cart = cart;
        this.cash = 0.0;
        this.am = 0.0;
        getContentPane().setBackground(Color.darkGray);
        initComponents();
    }
    
    public PaymentGUI(Customer current, Cart cart, double am, double cash) {
        this.current = current;
        this.cart = cart;
        this.am = am;
        this.cash = cash;
        getContentPane().setBackground(Color.darkGray);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectPayment = new javax.swing.JLabel();
        btnCash = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfReciept = new javax.swing.JEditorPane();
        btnCreditCard = new javax.swing.JButton();
        btnGiftCard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));

        lblSelectPayment.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblSelectPayment.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectPayment.setText("Select Payment");

        btnCash.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnCash.setText("Cash");
        btnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashActionPerformed(evt);
            }
        });

        tfReciept.setText(cart.showCart());
        tfReciept.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfRecieptPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tfReciept);

        btnCreditCard.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnCreditCard.setText("Credit Card");
        btnCreditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditCardActionPerformed(evt);
            }
        });

        btnGiftCard.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnGiftCard.setText("Gift Card");
        btnGiftCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiftCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelectPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGiftCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreditCard, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(btnCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelectPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCash, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGiftCard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(687, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfRecieptPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfRecieptPropertyChange
        if (am == 0) {
            //System.out.println("am==0 " + am);
            cart.showCart();
        } else {
            //System.out.println("else " + am);
            cart.showCartBalance(cash);
        }
    }//GEN-LAST:event_tfRecieptPropertyChange

    private void btnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashActionPerformed
        this.setVisible(false);
        new CashPaymentGUI(current, cart).setVisible(true);
    }//GEN-LAST:event_btnCashActionPerformed

    private void btnCreditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditCardActionPerformed
        this.setVisible(false);
        new CreditCardPaymentGUI(current, cart).setVisible(true);
    }//GEN-LAST:event_btnCreditCardActionPerformed

    private void btnGiftCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiftCardActionPerformed
        this.setVisible(false);
        new GiftCardPaymentGUI(current, cart).setVisible(true);
    }//GEN-LAST:event_btnGiftCardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCash;
    private javax.swing.JButton btnCreditCard;
    private javax.swing.JButton btnGiftCard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelectPayment;
    private javax.swing.JEditorPane tfReciept;
    // End of variables declaration//GEN-END:variables
}
