/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mjsanchez
 */
public class ReceiptGUI extends javax.swing.JFrame {
    private Customer customer;
    private Cart cart;
    private double am;
    private double paid;
    /**
     * Creates new form ReceiptGUI
     */
    public ReceiptGUI() {
        initComponents();
    }
    public ReceiptGUI(Customer customer, Cart cart, double am, double paid) {
        this.customer = customer;
        this.cart = cart;
        this.am = am;
        this.paid = paid;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taReceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        taReceipt.setColumns(20);
        taReceipt.setRows(5);
        taReceipt.setText(this.showReceipt());
        jScrollPane1.setViewportView(taReceipt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(307, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public String showReceipt() {
        String c;
        
        if (customer.getFirstName().equals("Guest")) {
            if (am == 0) {
                System.out.println("am==0 " + am);
                c = cart.showCart();
            } else {
                System.out.println("else " + am);
                c = cart.showCartReceipt(paid);
            }
            //c = cart.showCart();
            cart.setAmountPaidZero(0.0);
            cart.setTotal(0.0);
            cart.setTotalWithTax(0.0);
            return c;
        } else {
            if (am == 0) {
                System.out.println("am==0 " + am);
                double points = cart.getTotal() + cart.getTotal() * cart.getTax();
                customer.addPoints(points);
                double earned = points*2;
                c = cart.showCart() + "\n\n" + customer.getFirstName() + " you have earned " + String.format("%.2f", earned) + " points!";
                cart.setAmountPaidZero(0.0);
                cart.setTotal(0.0);
                cart.setTotalWithTax(0.0);
                return c;
            } else {
                System.out.println("else " + am);
                double points = cart.getTotal() + cart.getTotal() * cart.getTax();
                customer.addPoints(points);
                double earned = points*2;
                c = cart.showCartReceipt(paid) + "\n\n" + customer.getFirstName() + " you have earned " + String.format("%.2f", earned) + " points!";
                cart.setAmountPaidZero(0.0);
                cart.setTotal(0.0);
                cart.setTotalWithTax(0.0);
                return c;
            }
            //double points = cart.getTotal() + cart.getTotal() * cart.getTax();
//            customer.addPoints(points);
//            double earned = points*2;
//            c = cart.showCart(paid) + "\n\n" + customer.getFirstName() + " you have earned " + String.format("%.2f", earned) + " points!";
//            cart.setAmountPaidZero(0.0);
//            cart.setTotal(0.0);
//            cart.setTotalWithTax(0.0);
//            return c;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiptGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiptGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiptGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiptGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiptGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taReceipt;
    // End of variables declaration//GEN-END:variables
}
