/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cs234project;

import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author mjsanchez
 */
public class RegularSeatingGui extends javax.swing.JFrame {
    private Showtimes show;
    private String t;
    private Cart cart;
    /**
     * Creates new form RegularSeating
     */
    public RegularSeatingGui(Showtimes show, String t, Cart cart) {
        this.show = show;
        this.t = t;
        this.cart = cart;
        getContentPane().setBackground(Color.black);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butA01 = new javax.swing.JButton();
        butA02 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        butClose = new javax.swing.JButton();
        lblFOS = new javax.swing.JLabel();
        butA03 = new javax.swing.JButton();
        butA04 = new javax.swing.JButton();
        butA05 = new javax.swing.JButton();
        butA06 = new javax.swing.JButton();
        butA07 = new javax.swing.JButton();
        butA08 = new javax.swing.JButton();
        butA09 = new javax.swing.JButton();
        butA10 = new javax.swing.JButton();
        butA11 = new javax.swing.JButton();
        butA12 = new javax.swing.JButton();
        butA13 = new javax.swing.JButton();
        butA14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butA01.setText((show.getShowSeating()).get(0)
        );
        butA01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA01ActionPerformed(evt);
            }
        });

        butA02.setText((show.getShowSeating()).get(1));
        butA02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA02ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seat Selection:");

        lblSeats.setForeground(new java.awt.Color(255, 255, 255));
        lblSeats.setText(cart.getSeatSelections());

        butClose.setText("Done");
        butClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCloseActionPerformed(evt);
            }
        });

        lblFOS.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblFOS.setForeground(new java.awt.Color(255, 255, 255));
        lblFOS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFOS.setText("Front of Screen");

        butA03.setText((show.getShowSeating()).get(2));
        butA03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA03ActionPerformed(evt);
            }
        });

        butA04.setText((show.getShowSeating()).get(3));
        butA04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA04ActionPerformed(evt);
            }
        });

        butA05.setText((show.getShowSeating()).get(4));
        butA05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA05ActionPerformed(evt);
            }
        });

        butA06.setText((show.getShowSeating()).get(5));
        butA06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA06ActionPerformed(evt);
            }
        });

        butA07.setText((show.getShowSeating()).get(6));
        butA07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA07ActionPerformed(evt);
            }
        });

        butA08.setText((show.getShowSeating()).get(7));
        butA08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA08ActionPerformed(evt);
            }
        });

        butA09.setText((show.getShowSeating()).get(8));
        butA09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA09ActionPerformed(evt);
            }
        });

        butA10.setText((show.getShowSeating()).get(9));
        butA10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA10ActionPerformed(evt);
            }
        });

        butA11.setText((show.getShowSeating()).get(10));
        butA11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA11ActionPerformed(evt);
            }
        });

        butA12.setText((show.getShowSeating()).get(11));
        butA12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA12ActionPerformed(evt);
            }
        });

        butA13.setText((show.getShowSeating()).get(12));
        butA13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA13ActionPerformed(evt);
            }
        });

        butA14.setText((show.getShowSeating()).get(13));
        butA14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butA14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(butClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(butA01, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA02, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA03, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA04, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA05, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA06, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA07, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA08, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA09, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butA14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblFOS, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butA01)
                    .addComponent(butA02)
                    .addComponent(butA03)
                    .addComponent(butA04)
                    .addComponent(butA05)
                    .addComponent(butA06)
                    .addComponent(butA07)
                    .addComponent(butA08)
                    .addComponent(butA09)
                    .addComponent(butA10)
                    .addComponent(butA11)
                    .addComponent(butA12)
                    .addComponent(butA13)
                    .addComponent(butA14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSeats)
                    .addComponent(butClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butA01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA01ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A01".equals(seating.get(i))) {
                Seating seat = new Seating("A01", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA01.setText((show.getShowSeating()).get(0));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A01";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA01ActionPerformed

    private void butA02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA02ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A02".equals(seating.get(i))) {
                Seating seat = new Seating("A02", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA02.setText((show.getShowSeating()).get(1));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A02";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA02ActionPerformed

    private void butCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCloseActionPerformed
        this.setVisible(false); 
    }//GEN-LAST:event_butCloseActionPerformed

    private void butA03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA03ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A03".equals(seating.get(i))) {
                Seating seat = new Seating("A03", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA03.setText((show.getShowSeating()).get(2));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A03";
                lblSeats.setText(newSeats);
            }
        } 
    }//GEN-LAST:event_butA03ActionPerformed

    private void butA04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA04ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A04".equals(seating.get(i))) {
                Seating seat = new Seating("A04", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA04.setText((show.getShowSeating()).get(3));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A04";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA04ActionPerformed

    private void butA05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA05ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A05".equals(seating.get(i))) {
                Seating seat = new Seating("A05", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA05.setText((show.getShowSeating()).get(4));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A05";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA05ActionPerformed

    private void butA06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA06ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A06".equals(seating.get(i))) {
                Seating seat = new Seating("A06", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA06.setText((show.getShowSeating()).get(5));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A06";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA06ActionPerformed

    private void butA07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA07ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A07".equals(seating.get(i))) {
                Seating seat = new Seating("A07", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA07.setText((show.getShowSeating()).get(6));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A07";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA07ActionPerformed

    private void butA08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA08ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A08".equals(seating.get(i))) {
                Seating seat = new Seating("A08", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA08.setText((show.getShowSeating()).get(7));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A08";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA08ActionPerformed

    private void butA09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA09ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A09".equals(seating.get(i))) {
                Seating seat = new Seating("A09", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA09.setText((show.getShowSeating()).get(8));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A09";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA09ActionPerformed

    private void butA10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA10ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A10".equals(seating.get(i))) {
                Seating seat = new Seating("A10", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA10.setText((show.getShowSeating()).get(9));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A10";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA10ActionPerformed

    private void butA11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA11ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A11".equals(seating.get(i))) {
                Seating seat = new Seating("A11", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA11.setText((show.getShowSeating()).get(10));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A11";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA11ActionPerformed

    private void butA12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA12ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A12".equals(seating.get(i))) {
                Seating seat = new Seating("A12", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA12.setText((show.getShowSeating()).get(11));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A12";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA12ActionPerformed

    private void butA13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA13ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A13".equals(seating.get(i))) {
                Seating seat = new Seating("A13", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA13.setText((show.getShowSeating()).get(12));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A13";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA13ActionPerformed

    private void butA14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butA14ActionPerformed
        ArrayList<String> seating = new ArrayList<>();
        seating = show.getShowSeating();

        for (int i = 0; i < seating.size(); i++) {
            if ("A14".equals(seating.get(i))) {
                Seating seat = new Seating("A14", t);
                cart.addSeat(seat);
                show.seatsTaken(cart, show);
                butA14.setText((show.getShowSeating()).get(13));
                String newSeats = lblSeats.getText();
                newSeats = newSeats + " A14";
                lblSeats.setText(newSeats);
            }
        }
    }//GEN-LAST:event_butA14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegularSeatingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegularSeatingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegularSeatingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegularSeatingGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RegularSeating().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butA01;
    private javax.swing.JButton butA02;
    private javax.swing.JButton butA03;
    private javax.swing.JButton butA04;
    private javax.swing.JButton butA05;
    private javax.swing.JButton butA06;
    private javax.swing.JButton butA07;
    private javax.swing.JButton butA08;
    private javax.swing.JButton butA09;
    private javax.swing.JButton butA10;
    private javax.swing.JButton butA11;
    private javax.swing.JButton butA12;
    private javax.swing.JButton butA13;
    private javax.swing.JButton butA14;
    private javax.swing.JButton butClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFOS;
    private javax.swing.JLabel lblSeats;
    // End of variables declaration//GEN-END:variables
}
