/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cs234project;

import java.awt.Color;

/**
 *
 * @author mjsanchez
 */
public class StaffMenuGui extends javax.swing.JFrame {

    /**
     * Creates new form MainGui
     */
    public StaffMenuGui() {
        initComponents();
        
        getContentPane().setBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butRegNewStaff = new javax.swing.JButton();
        butCustReg = new javax.swing.JButton();
        butCustMainMenu = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Theater");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        butRegNewStaff.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butRegNewStaff.setText("Register New Staff");
        butRegNewStaff.setAutoscrolls(true);
        butRegNewStaff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butRegNewStaff.setContentAreaFilled(false);
        butRegNewStaff.setOpaque(true);
        butRegNewStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegNewStaffActionPerformed(evt);
            }
        });
        getContentPane().add(butRegNewStaff);
        butRegNewStaff.setBounds(150, 140, 240, 58);

        butCustReg.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butCustReg.setText("Remove Staff");
        butCustReg.setAutoscrolls(true);
        butCustReg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butCustReg.setContentAreaFilled(false);
        butCustReg.setOpaque(true);
        getContentPane().add(butCustReg);
        butCustReg.setBounds(150, 220, 240, 58);

        butCustMainMenu.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butCustMainMenu.setText("Display Members List");
        butCustMainMenu.setAutoscrolls(true);
        butCustMainMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butCustMainMenu.setContentAreaFilled(false);
        butCustMainMenu.setOpaque(true);
        getContentPane().add(butCustMainMenu);
        butCustMainMenu.setBounds(150, 300, 240, 58);

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Generic");
        getContentPane().add(lblTitle1);
        lblTitle1.setBounds(110, 30, 198, 46);

        lblTitle2.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 153, 0));
        lblTitle2.setText("Movie Theater");
        getContentPane().add(lblTitle2);
        lblTitle2.setBounds(190, 60, 255, 56);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 373, 240, 40);

        setSize(new java.awt.Dimension(543, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butRegNewStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegNewStaffActionPerformed
        //this.setVisible(false); new CustomerMenu().setVisible(true);
    }//GEN-LAST:event_butRegNewStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffMenuGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCustMainMenu;
    private javax.swing.JButton butCustReg;
    private javax.swing.JButton butRegNewStaff;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    // End of variables declaration//GEN-END:variables
}
