/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cs234project;


import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author mjsanchez
 */
public class StaffMenuGui extends javax.swing.JFrame {
    private Customer current;
    private Staff staff;
    private Membership mem;
    private Authentication obauth;
    private EmployeeManager objman;
    private Authentication objauth;
    private Inventory inventory;
    private Cart cart;
    private HashSet<Customer> hashset;
    private ArrayList<Staff> alist;
    private ArrayList<Concession> prod;
    private ArrayList<Showtimes> shows;

    /**
     * Creates new form MainGui
     */
 
    public StaffMenuGui(Customer customer, Staff staff, HashSet<Customer> hashset, Membership mem, Authentication obauth, ArrayList<Staff> alist, EmployeeManager objman, Authentication objauth, Inventory inventory, ArrayList<Concession> prod, Cart cart, ArrayList<Showtimes> shows){
        this.current = new Customer();
        this.staff = staff;
        this.hashset = hashset;
        this.mem = mem;
        this.obauth = obauth;
        this.alist = alist;
        this.objman = objman;
        this.objauth = objauth;
        this.inventory = inventory;
        this.prod =prod;
        this.cart = cart;
        this.shows = shows;
        initComponents();
        
        getContentPane().setBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butDisplayStaff = new javax.swing.JButton();
        butDisplayMembersList = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        butMainMenu = new javax.swing.JButton();
        butInventoryMenu1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Theater");
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(null);

        butDisplayStaff.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butDisplayStaff.setText("Employee Managment");
        butDisplayStaff.setAutoscrolls(true);
        butDisplayStaff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butDisplayStaff.setContentAreaFilled(false);
        butDisplayStaff.setOpaque(true);
        butDisplayStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDisplayStaffActionPerformed(evt);
            }
        });
        getContentPane().add(butDisplayStaff);
        butDisplayStaff.setBounds(140, 140, 250, 50);

        butDisplayMembersList.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butDisplayMembersList.setText("Display Members List");
        butDisplayMembersList.setAutoscrolls(true);
        butDisplayMembersList.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butDisplayMembersList.setContentAreaFilled(false);
        butDisplayMembersList.setOpaque(true);
        butDisplayMembersList.setPreferredSize(new java.awt.Dimension(184, 38));
        butDisplayMembersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDisplayMembersListActionPerformed(evt);
            }
        });
        getContentPane().add(butDisplayMembersList);
        butDisplayMembersList.setBounds(140, 200, 250, 50);

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Generic");
        getContentPane().add(lblTitle1);
        lblTitle1.setBounds(110, 30, 198, 46);

        lblTitle2.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 153, 0));
        lblTitle2.setText("Movie Theater");
        getContentPane().add(lblTitle2);
        lblTitle2.setBounds(190, 60, 255, 57);

        butMainMenu.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butMainMenu.setText("Main Menu");
        butMainMenu.setAutoscrolls(true);
        butMainMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butMainMenu.setContentAreaFilled(false);
        butMainMenu.setOpaque(true);
        butMainMenu.setPreferredSize(new java.awt.Dimension(184, 38));
        butMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMainMenuActionPerformed(evt);
            }
        });
        getContentPane().add(butMainMenu);
        butMainMenu.setBounds(140, 310, 250, 40);

        butInventoryMenu1.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butInventoryMenu1.setText("Inventory Menu");
        butInventoryMenu1.setAutoscrolls(true);
        butInventoryMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butInventoryMenu1.setContentAreaFilled(false);
        butInventoryMenu1.setOpaque(true);
        butInventoryMenu1.setPreferredSize(new java.awt.Dimension(184, 38));
        butInventoryMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInventoryMenu1ActionPerformed(evt);
            }
        });
        getContentPane().add(butInventoryMenu1);
        butInventoryMenu1.setBounds(140, 260, 250, 40);

        setSize(new java.awt.Dimension(529, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butDisplayMembersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDisplayMembersListActionPerformed
        JOptionPane.showMessageDialog(this, mem.getMembers());
    }//GEN-LAST:event_butDisplayMembersListActionPerformed

    private void butMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMainMenuActionPerformed
        this.setVisible(false); new MainGui(current, staff, hashset, mem, obauth, alist, objman, objauth, inventory, prod, cart, shows).setVisible(true);
    }//GEN-LAST:event_butMainMenuActionPerformed

    private void butDisplayStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDisplayStaffActionPerformed
        this.setVisible(false);new EmployeeRoster(current, staff, hashset, mem, obauth, alist, objman, objauth, inventory, prod, cart, shows).setVisible(true);
    }//GEN-LAST:event_butDisplayStaffActionPerformed

    private void butInventoryMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInventoryMenu1ActionPerformed
        this.setVisible(false);new InventoryMenuGui(current, staff, hashset, mem, obauth, alist, objman, objauth, inventory, prod, cart, shows).setVisible(true);
    }//GEN-LAST:event_butInventoryMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffMenuGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDisplayMembersList;
    private javax.swing.JButton butDisplayStaff;
    private javax.swing.JButton butInventoryMenu1;
    private javax.swing.JButton butMainMenu;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    // End of variables declaration//GEN-END:variables
}
