package com.mycompany.cs234project;
import com.mycompany.cs234project.Authentication;
import com.mycompany.cs234project.Staff;
import com.mycompany.cs234project.EmployeeManager;
import java.awt.Color;
import java.util.HashSet;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jbock
 */
public class StaffRegistrationGUI extends javax.swing.JFrame {
    private Staff newStaf;
    private EmployeeManager objman;
    private ArrayList<Staff> alist;
    private Authentication objauth;

    /**
     * Creates new form StaffRegistrationGUI
     */
    public StaffRegistrationGUI(ArrayList<Staff> alist, EmployeeManager objman, Authentication objauth) {
        newStaf=new Staff();
        this.objman=objman;
        this.alist=alist;
        this.objauth=objauth;
         initComponents();
        getContentPane().setBackground(Color.black);
        
    }

    private StaffRegistrationGUI() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        tfPosition1 = new javax.swing.JTextField();
        tfTextField3 = new javax.swing.JTextField();
        tfTextField2 = new javax.swing.JTextField();
        tfTextField4 = new javax.swing.JTextField();
        tfPayRate5 = new javax.swing.JTextField();
        tfTextField5 = new javax.swing.JTextField();
        tfUserName7 = new javax.swing.JTextField();
        tfTextField6 = new javax.swing.JTextField();
        tfPassword9 = new javax.swing.JTextField();
        tfFirstName10 = new javax.swing.JTextField();
        tfTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Staff Registration");

        tfLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLastNameActionPerformed(evt);
            }
        });

        tfPosition1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPosition1ActionPerformed(evt);
            }
        });

        tfTextField3.setEditable(false);
        tfTextField3.setText("Position Title");
        tfTextField3.setOpaque(true);
        tfTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTextField3ActionPerformed(evt);
            }
        });

        tfTextField2.setEditable(false);
        tfTextField2.setText("Last Name");
        tfTextField2.setOpaque(true);
        tfTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTextField2ActionPerformed(evt);
            }
        });

        tfTextField4.setEditable(false);
        tfTextField4.setText("Pay Rate");
        tfTextField4.setOpaque(true);
        tfTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTextField4ActionPerformed(evt);
            }
        });

        tfPayRate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPayRate5ActionPerformed(evt);
            }
        });

        tfTextField5.setEditable(false);
        tfTextField5.setText("Username");
        tfTextField5.setOpaque(true);
        tfTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTextField5ActionPerformed(evt);
            }
        });

        tfUserName7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserName7ActionPerformed(evt);
            }
        });

        tfTextField6.setEditable(false);
        tfTextField6.setText("Password");
        tfTextField6.setOpaque(true);
        tfTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTextField6ActionPerformed(evt);
            }
        });

        tfPassword9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassword9ActionPerformed(evt);
            }
        });

        tfFirstName10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFirstName10ActionPerformed(evt);
            }
        });

        tfTextField1.setEditable(false);
        tfTextField1.setText("First Name");
        tfTextField1.setOpaque(true);
        tfTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPosition1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPayRate5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUserName7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPassword9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFirstName10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(158, 158, 158))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tfFirstName10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPosition1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPayRate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfUserName7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPassword9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLastNameActionPerformed

    }//GEN-LAST:event_tfLastNameActionPerformed

    private void tfPosition1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPosition1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPosition1ActionPerformed

    private void tfTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTextField3ActionPerformed

    private void tfTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTextField2ActionPerformed

    private void tfTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTextField4ActionPerformed

    private void tfPayRate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPayRate5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPayRate5ActionPerformed

    private void tfTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTextField5ActionPerformed

    private void tfUserName7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserName7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUserName7ActionPerformed

    private void tfTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTextField6ActionPerformed

    private void tfPassword9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassword9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassword9ActionPerformed

    private void tfFirstName10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstName10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFirstName10ActionPerformed

    private void tfTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String firstName=tfFirstName10.getText();
        newStaf.setFirstName(firstName);
        String lastName=tfLastName.getText();
        newStaf.setLastName(lastName);
        String position=tfPosition1.getText();
        newStaf.setPosition(position);
        double payRate=Double.parseDouble(tfPayRate5.getText());
        newStaf.setPay(payRate);
        String userName=tfUserName7.getText();
        newStaf.setUserName(userName);
        String password=tfPassword9.getText();
        newStaf.setPassword(password);
        objman.addEmployee(newStaf);
        JOptionPane.showMessageDialog(this, "Registration Successful!");
                this.setVisible(false);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffRegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffRegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffRegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffRegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffRegistrationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfFirstName10;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JTextField tfPassword9;
    private javax.swing.JTextField tfPayRate5;
    private javax.swing.JTextField tfPosition1;
    private javax.swing.JTextField tfTextField1;
    private javax.swing.JTextField tfTextField2;
    private javax.swing.JTextField tfTextField3;
    private javax.swing.JTextField tfTextField4;
    private javax.swing.JTextField tfTextField5;
    private javax.swing.JTextField tfTextField6;
    private javax.swing.JTextField tfUserName7;
    // End of variables declaration//GEN-END:variables
}
