/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


//imports
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author mjsanchez
 */

//setting instance variables
public class TransactionMenuGUI extends javax.swing.JFrame {
    private Customer current;
    private Staff staff;
    private Membership mem;
    private Authentication obauth;
    private EmployeeManager objman;
    private Authentication objauth;
    private Inventory inventory;
    private Cart cart;
    private HashSet<Customer> hashset;
    private ArrayList<Staff> alist;
    private ArrayList<Concession> prod;
    private ArrayList<Showtimes> shows;
    /**
     * Creates new form MainGui
     */
    public TransactionMenuGUI () {
        
    }
    //intializes instance variables
    public TransactionMenuGUI(Customer customer, Staff staff, HashSet<Customer> hashset, Membership mem, Authentication obauth, ArrayList<Staff> alist, EmployeeManager objman, Authentication objauth, Inventory inventory, ArrayList<Concession> prod, Cart cart, ArrayList<Showtimes> shows) {
        current = customer;
        this.staff = staff;
        this.hashset = hashset;
        this.mem = mem;
        this.obauth = obauth;
        this.alist = alist;
        this.objman = objman;
        this.objauth = objauth;
        this.inventory = inventory;
        this.prod = prod;
        this.cart = cart;
        this.shows = shows;
        initComponents();
        
        //sets background color
        Color col = new Color(153, 0, 0);
        getContentPane().setBackground(col);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butBuyTickets = new javax.swing.JButton();
        butConcession = new javax.swing.JButton();
        butMainMenu = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        butPayment = new javax.swing.JButton();
        lblCustomerOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movie Theater");
        setBackground(new java.awt.Color(204, 0, 0));
        getContentPane().setLayout(null);

        butBuyTickets.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butBuyTickets.setText("Buy Tickets");
        butBuyTickets.setAutoscrolls(true);
        butBuyTickets.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butBuyTickets.setContentAreaFilled(false);
        butBuyTickets.setOpaque(true);
        butBuyTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuyTicketsActionPerformed(evt);
            }
        });
        getContentPane().add(butBuyTickets);
        butBuyTickets.setBounds(150, 140, 220, 58);

        butConcession.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butConcession.setText("Concession");
        butConcession.setAutoscrolls(true);
        butConcession.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butConcession.setContentAreaFilled(false);
        butConcession.setOpaque(true);
        butConcession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConcessionActionPerformed(evt);
            }
        });
        getContentPane().add(butConcession);
        butConcession.setBounds(150, 220, 220, 58);

        butMainMenu.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butMainMenu.setText("Exit to Main Menu");
        butMainMenu.setAutoscrolls(true);
        butMainMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butMainMenu.setContentAreaFilled(false);
        butMainMenu.setOpaque(true);
        butMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMainMenuActionPerformed(evt);
            }
        });
        getContentPane().add(butMainMenu);
        butMainMenu.setBounds(150, 380, 220, 58);

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Purchase Menu");
        getContentPane().add(lblTitle1);
        lblTitle1.setBounds(80, 20, 380, 46);

        butPayment.setFont(new java.awt.Font("Canela Text", 0, 24)); // NOI18N
        butPayment.setText("Payment");
        butPayment.setAutoscrolls(true);
        butPayment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51), new java.awt.Color(153, 51, 0), new java.awt.Color(204, 102, 0)));
        butPayment.setContentAreaFilled(false);
        butPayment.setOpaque(true);
        butPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(butPayment);
        butPayment.setBounds(150, 300, 220, 58);

        lblCustomerOutput.setFont(new java.awt.Font("Charmonman", 1, 24)); // NOI18N
        lblCustomerOutput.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerOutput.setText("Welcome  " + current.getFirstName());
        getContentPane().add(lblCustomerOutput);
        lblCustomerOutput.setBounds(100, 80, 310, 40);

        setSize(new java.awt.Dimension(542, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butBuyTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuyTicketsActionPerformed
        //opens movie selection screen
        new MovieSelectionGUI2(inventory, cart, shows).setVisible(true);
    }//GEN-LAST:event_butBuyTicketsActionPerformed

    private void butMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMainMenuActionPerformed
       //opens main menu
        this.setVisible(false); new MainGui(current, staff, hashset, mem, obauth, alist, objman, objauth, inventory, prod, cart, shows).setVisible(true);
    }//GEN-LAST:event_butMainMenuActionPerformed

    private void butPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPaymentActionPerformed
       //opens payment screen
        new PaymentGUI(current, cart).setVisible(true);
    }//GEN-LAST:event_butPaymentActionPerformed

    private void butConcessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConcessionActionPerformed
       //opens conceccion menu
        new ConcessionMenuGUI(inventory, prod, cart).setVisible(true);
    }//GEN-LAST:event_butConcessionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //String name = current.getFirstName();
        //lblCustomerOutput.setText("Name");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionMenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBuyTickets;
    private javax.swing.JButton butConcession;
    private javax.swing.JButton butMainMenu;
    private javax.swing.JButton butPayment;
    private javax.swing.JLabel lblCustomerOutput;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
